"""Seed menu items parsed from misc2/prompt2.txt with extras for small categories."""

import re

# Parsed from prompt2.txt - each category maps to list of (name, price, description)
MENU_DATA = {
    "Acai Bowls": [
        ("Acai Bowl", 12.97, "Acai, Banana, Blueberry, Strawberry, Granola, Coconut, Honey"),
        ("Tropical Acai Bowl", 13.97, "Acai, Mango, Pineapple, Coconut, Granola, Honey"),
        ("Berry Blast Bowl", 13.97, "Acai, Blueberry, Raspberry, Strawberry, Granola, Almond Butter"),
        ("Green Acai Bowl", 13.47, "Acai, Spinach, Banana, Kiwi, Granola, Chia Seeds"),
        ("PB Acai Bowl", 14.47, "Acai, Peanut Butter, Banana, Granola, Chocolate Chips"),
        ("Dragon Fruit Bowl", 14.97, "Dragon Fruit, Acai, Strawberry, Coconut, Granola"),
        ("Nutty Acai Bowl", 14.47, "Acai, Almonds, Walnuts, Banana, Honey, Granola"),
        ("Island Acai Bowl", 13.97, "Acai, Papaya, Mango, Macadamia, Coconut, Honey"),
        ("Sunrise Bowl", 12.97, "Acai, Orange, Peach, Granola, Honey"),
        ("Chocolate Acai Bowl", 14.47, "Acai, Cocoa, Banana, Almond Milk, Granola"),
        ("Protein Acai Bowl", 15.97, "Acai, Whey Protein, Banana, Peanut Butter, Granola"),
        ("Matcha Acai Bowl", 14.97, "Acai, Matcha, Banana, Coconut, Hemp Seeds"),
        ("Superfood Bowl", 15.47, "Acai, Goji Berries, Chia Seeds, Flax, Banana, Honey"),
        ("Mango Tango Bowl", 13.47, "Acai, Mango, Passion Fruit, Coconut, Granola"),
        ("Classic Banana Bowl", 12.47, "Acai, Banana, Strawberry, Granola, Honey Drizzle"),
    ],
    "Bottled Drinks": [
        ("Apple Juice", 3.59, ""), ("Arizona Iced Cold Brew Green Tea", 4.09, ""),
        ("Arizona Iced Cold Brew Iced Tea", 4.09, ""), ("Arizona Iced Cold Brew Sweet Tea", 4.09, ""),
        ("Coke 20oz soda", 3.59, ""), ("Cranberry Juice", 3.59, ""),
        ("Diet Coke 20oz soda", 3.59, ""), ("Diet Dr. Pepper 20oz soda", 3.59, ""),
        ("Dr. Pepper 20oz soda", 3.59, ""), ("Essentia 1 L", 4.89, ""),
        ("Gatorade Cool Blue", 3.59, ""), ("Gatorade Fruit Punch", 3.59, ""),
        ("Gatorade Lemon Lime", 3.59, ""), ("Gatorade Orange", 3.59, ""),
        ("Grape Juice", 3.59, ""), ("Monster", 3.50, ""),
        ("Monster Zero Sugar", 3.50, ""), ("Orange Juice", 3.59, "OJ"),
        ("Pepsi 20oz soda", 3.59, ""), ("Poland Spring Water 500 mL", 2.55, ""),
        ("Poland Spring Water 1 L", 4.23, ""), ("Red Bull 8.4 oz.", 2.95, ""),
        ("Red Bull Sugar Free 8.4 oz", 2.95, ""), ("Snapple 16 oz Lemon Tea", 2.75, ""),
        ("Snapple 16 oz Peach Tea", 2.75, ""), ("Sprite 20oz soda", 3.59, ""),
        ("Vitamin Water XXX (Acai Blueberry Pomegranate)", 3.59, ""),
        ("Vitamin Water Essential (Orange)", 3.59, ""),
        ("Vitamin Water Power-C (Dragonfruit)", 3.59, ""),
        ("Vegetable Juice", 3.59, ""),
    ],
    "Breakfast Combos": [
        ("French Toast", 9.95, "Texas style french toast served with butter and syrup"),
        ("Healthy One", 11.64, "Three egg whites, turkey, spinach, Alpine Lace Swiss, in a whole wheat wrap."),
        ("Hungry Man", 12.95, "Three eggs, ham, bacon, sausage, and cheese on a hero."),
        ("Melville Platter", 12.95, "Two eggs, ham, bacon, sausage, home-fries, and toast."),
        ("Protein Slammer", 12.94, "Five egg whites, extra turkey, Alpine Lace Swiss cheese, on a whole wheat wrap."),
        ("Super Thing", 12.94, "Two eggs, extra bacon, extra sausage, onions, and American cheese."),
        ("Pancake Stack", 10.95, "Three fluffy buttermilk pancakes with maple syrup and butter"),
        ("Egg & Cheese Platter", 9.95, "Two eggs any style with cheese, home-fries, and toast"),
        ("Veggie Sunrise", 11.64, "Egg whites, avocado, spinach, tomato, Swiss on whole wheat"),
        ("Bacon Lover's Special", 13.95, "Three eggs, extra bacon, cheddar cheese on a hero"),
        ("Sausage & Egg Combo", 11.95, "Two eggs, sausage patties, home-fries, and toast"),
        ("Greek Breakfast", 12.64, "Egg whites, feta, tomato, spinach, olives on pita"),
        ("Ham & Swiss Platter", 12.95, "Two eggs, Virginia ham, Swiss cheese, home-fries"),
        ("Country Breakfast", 14.95, "Three eggs, steak, home-fries, toast, and onions"),
        ("Light Start", 8.95, "One egg, turkey bacon, whole wheat toast"),
    ],
    "BYO Breakfast": [
        ("Bagel", 0.00, "Build your own bagel with spreads"),
        ("Breakfast", 2.60, "Build your own breakfast sandwich"),
    ],
    "BYO Sandwiches": [
        ("BYO Sandwiches", 16.00, "Build your own sandwich with bread, protein, cheese, toppings"),
    ],
    "Chips": [
        ("Classic Lays", 3.24, ""), ("Cool Ranch Doritos", 3.24, ""),
        ("Nacho Cheese Doritos", 3.24, ""), ("Spicy Sweet Chili Doritos", 3.24, ""),
        ("Kettle Cooked Sea Salt", 3.24, ""), ("BBQ Lays", 3.24, ""),
        ("Sour Cream & Onion Lays", 3.24, ""), ("Cheddar & Sour Cream Ruffles", 3.24, ""),
        ("Flamin Hot Cheetos", 3.24, ""), ("Baked Lays", 3.24, ""),
        ("Salt & Vinegar Chips", 3.24, ""), ("Tostitos Scoops", 3.24, ""),
        ("Sun Chips Harvest Cheddar", 3.24, ""), ("Funyuns", 3.24, ""),
        ("Pringles Original", 3.24, ""),
    ],
    "Chopped Salad": [
        ("BYO Salad", 9.95, "Build your own chopped salad with base, toppings, and dressing"),
    ],
    "Coffee": [
        ("Cappuccino, Large", 2.76, ""), ("Cappuccino, Medium", 2.25, ""), ("Cappuccino, Small", 1.76, ""),
        ("French Vanilla, Large", 2.76, ""), ("French Vanilla, Medium", 2.25, ""), ("French Vanilla, Small", 1.76, ""),
        ("Columbian Coffee, Large", 2.76, ""), ("Columbian Coffee, Medium", 2.25, ""), ("Columbian Coffee, Small", 1.76, ""),
        ("Hot Coffee, Large", 2.76, ""), ("Hot Coffee, Medium", 2.25, ""), ("Hot Coffee, Small", 1.76, ""),
        ("Hot Decaf Coffee, Large", 2.76, ""), ("Hot Decaf Coffee, Medium", 2.25, ""), ("Hot Decaf Coffee, Small", 1.76, ""),
    ],
    "Tea": [
        ("Green Tea, Large", 2.76, ""), ("Green Tea, Medium", 2.25, ""), ("Green Tea, Small", 1.76, ""),
        ("Green Decaf Tea, Large", 2.76, ""), ("Green Decaf Tea, Medium", 2.25, ""), ("Green Decaf Tea, Small", 1.76, ""),
        ("Hot Tea, Large", 2.76, ""), ("Hot Tea, Medium", 2.25, ""), ("Hot Tea, Small", 1.76, ""),
        ("Hot Decaf Tea, Large", 2.76, ""), ("Hot Decaf Tea, Medium", 2.25, ""), ("Hot Decaf Tea, Small", 1.76, ""),
        ("Chamomile Tea, Large", 2.76, ""), ("Chamomile Tea, Medium", 2.25, ""), ("Chamomile Tea, Small", 1.76, ""),
    ],
    "Cold Sandwiches": [
        ("Balsamic Avocado Hero", 17.95, "Turkey breast, avocado, tomato, romaine lettuce and balsamic vinaigrette."),
        ("Cajun Roast Beef Hero", 17.95, "Cajun roast beef, Cheddar cheese, lettuce, roasted red peppers and creole mayo."),
        ("California Hero", 17.95, "Turkey breast, avocado, lettuce, tomatoes and Russian dressing."),
        ("Chicken Knock Out Hero", 17.95, "Fried chicken cutlet, hot cherry peppers, jalapeño Jack cheese, lettuce, tomato, and horseradish dressing."),
        ("Dagwood Hero", 17.95, "Roast beef, turkey, ham, American, Swiss, lettuce, tomato, and mayo."),
        ("Grandpa Ted Hero", 17.95, "Turkey breast, Genoa salami, cole-slaw and mustard."),
        ("Honey Dipped Chicken Hero", 17.95, "Chicken cutlet, Cheddar cheese, romaine lettuce, tomato, and honey dip sauce."),
        ("Italian Grilled Chicken Hero", 17.95, "Grilled chicken, lettuce, roasted red peppers, fresh Mozzarella and pesto sauce."),
        ("Italian Hero", 17.95, "Capicola ham, salami, pepperoni, lettuce, tomato, Provolone cheese and Italian dressing on a hero"),
        ("Monte Christo Hero", 17.95, "Turkey breast, ham, Swiss cheese, lettuce, tomato and Russian dressing."),
        ("Nazareth Hero", 17.95, "Fried chicken cutlet, bacon, Swiss cheese, cole-slaw and Russian dressing."),
        ("Roast Beef Deluxe Hero", 17.95, "Roast beef, bacon, Cheddar, lettuce, tomato and mayo."),
        ("Turkey Club Hero", 17.95, "Roast turkey breast, bacon, lettuce, tomato and mayo on a hero."),
        ("Smoked Turkey Avocado Hero", 17.95, "Smoked turkey, avocado, Swiss cheese, lettuce, tomato, ranch"),
        ("Chicken Caesar Hero", 17.95, "Grilled chicken, romaine, parmesan, caesar dressing on a hero"),
    ],
    "Desserts": [
        ("Chocolate Chip Cookies", 2.29, ""),
        ("Chocolate Pudding", 3.89, ""),
        ("Rice Pudding", 4.54, ""),
        ("Brownie", 3.49, "Rich chocolate brownie"),
        ("Vanilla Pudding", 3.89, "Classic vanilla pudding"),
        ("Sugar Cookie", 2.29, "Frosted sugar cookie"),
        ("Cheesecake Slice", 5.99, "New York style cheesecake"),
        ("Apple Pie Slice", 4.99, "Classic apple pie"),
        ("Carrot Cake", 5.49, "With cream cheese frosting"),
        ("Tiramisu Cup", 5.99, "Classic Italian tiramisu"),
        ("Lemon Bar", 3.49, "Tangy lemon bar"),
        ("Oatmeal Raisin Cookie", 2.29, "Soft oatmeal raisin cookie"),
        ("Red Velvet Cookie", 2.79, "Red velvet with cream cheese"),
        ("Banana Bread Slice", 3.99, "Fresh baked banana bread"),
        ("Cinnamon Roll", 4.49, "Warm cinnamon roll with icing"),
    ],
    "Grill Menu": [
        ("Beef gyro", 12.94, "Lettuce, tomato, cucumbers, onions, gyro sauce."),
        ("Cuban Sandwich", 18.12, "Pulled pork, ham, Swiss cheese, pickles and tomatoes on a garlic bread hero."),
        ("Falafel Wrap", 11.64, "Falafel, lettuce, onion, cucumber, tomato and tahini sauce."),
        ("Grilled Monte Cristo", 16.84, "Ham, turkey, Swiss cheese, Russian dressing and tomato on Texas style bread."),
        ("Philly Cheese Steak", 14.24, "Tender rib-eye steak, sautéed peppers, onions, and mixed Cheese."),
        ("Wrap Supreme", 11.64, "Chicken tenders, lettuce, tomato, cheese, and ranch dressing."),
        ("Chicken Quesadilla", 13.94, "Grilled chicken, mixed cheese, peppers, onions in a flour tortilla"),
        ("Steak Quesadilla", 15.94, "Sliced steak, cheddar, onions, peppers in a flour tortilla"),
        ("Grilled Chicken Wrap", 12.64, "Grilled chicken, lettuce, tomato, ranch in a wheat wrap"),
        ("Buffalo Chicken Wrap", 13.64, "Crispy chicken, buffalo sauce, lettuce, blue cheese dressing"),
        ("Turkey Burger", 12.94, "Turkey patty, lettuce, tomato, onion on a brioche bun"),
        ("Classic Hamburger", 13.94, "Beef patty, lettuce, tomato, onion, pickles on a brioche bun"),
        ("Bacon Cheeseburger", 15.94, "Beef patty, bacon, cheddar, lettuce, tomato"),
        ("Veggie Burger", 12.94, "Plant-based patty, lettuce, tomato, avocado"),
        ("Fish Tacos", 14.94, "Grilled fish, cabbage slaw, chipotle mayo, corn tortillas"),
    ],
    "Hot Sandwiches": [
        ("Chicken Fiesta Hero", 17.95, "Fried chicken cutlet, fresh mozzarella, roasted red peppers and spicy mayo on a toasted hero."),
        ("Chicken Italian Melt Hero", 17.95, "Fried chicken cutlet, mozzarella cheese, lettuce, tomato, onions, oil, vinegar on a toasted hero."),
        ("Dare Devil Hero", 17.95, "Fried chicken cutlet, cheddar cheese, potato salad, lettuce and Russian dressing on a toasted hero"),
        ("Half Hollow Hero", 17.95, "Sliced buffalo chicken, bacon, mozzarella, lettuce, tomato and Bleu cheese on a toasted garlic hero."),
        ("Mac-Truck Hero", 17.95, "Fried chicken cutlet, Mozzarella, mac salad, bacon and honey mustard on a toasted garlic hero."),
        ("Melville Spice Hero", 17.95, "Fried cajun chicken cutlet, bacon, cheddar cheese, lettuce, tomato, and Russian dressing on a toasted hero."),
        ("Original Hero", 17.95, "Fried chicken cutlet, cucumber, lettuce, tomato, Mozzarella, ranch and hot sauce on a toasted hero."),
        ("Passport Hero", 17.95, "Fried chicken cutlet, bacon, lettuce, ranch, barbeque sauce, American cheese on a toasted hero."),
        ("Pat's Fiesta Hero", 17.95, "Fried chicken cutlet, roasted red peppers, Pecorino cheese, fresh Mozzarella, pesto sauce, toasted hero."),
        ("Route 110 Hero", 17.95, "Grilled chicken, turkey, roasted red pepper, Jack cheese, lettuce and pesto sauce on a toasted hero."),
        ("Southern Ranch Hero", 17.95, "Roast beef, roasted red peppers, Jack cheese, lettuce and ranch dressing on a toasted garlic hero."),
        ("Spicy CAB Ride Hero", 17.95, "Fried chicken cutlet, avocado, bacon, mozzarella, cheddar, lettuce, tomato and spicy mayo on a toasted hero."),
        ("Sweet Hills Hero", 17.95, "Honey turkey, bacon, Cheddar, Mozzarella, lettuce, and honey mustard on a toasted hero."),
        ("Texas Hero", 17.95, "Fried chicken cutlet, bacon, fried onions, Mozzarella, Cheddar and barbeque sauce on a toasted garlic hero."),
        ("X-Factor Hero", 17.95, "Fried chicken cutlet, mozzarella cheese, bacon, cole-slaw and Russian dressing on a toasted garlic hero."),
    ],
    "Iced Tea and Lemonade": [
        ("Home-Made Iced Tea, Large", 3.50, ""), ("Home-Made Iced Tea, Medium", 2.76, ""),
        ("Home-Made Lemonade, Large", 3.50, ""), ("Home-Made Lemonade, Medium", 2.76, ""),
        ("Unsweetened Iced Tea, Large", 3.50, ""), ("Unsweetened Iced Tea, Medium", 2.76, ""),
        ("Arnold Palmer, Large", 3.50, "Half iced tea, half lemonade"), ("Arnold Palmer, Medium", 2.76, ""),
        ("Raspberry Lemonade, Large", 3.75, ""), ("Raspberry Lemonade, Medium", 3.00, ""),
        ("Peach Iced Tea, Large", 3.50, ""), ("Peach Iced Tea, Medium", 2.76, ""),
        ("Mint Lemonade, Large", 3.75, ""), ("Mint Lemonade, Medium", 3.00, ""),
        ("Strawberry Lemonade, Large", 3.75, ""), ("Strawberry Lemonade, Medium", 3.00, ""),
    ],
    "Muffins & Pastries": [
        ("Apple Turnover", 3.59, ""), ("Banana Nut Muffin", 3.59, ""),
        ("Blueberry Muffin", 3.59, ""), ("Bran Muffin", 3.59, ""),
        ("Cheese Danish", 3.59, ""), ("Chocolate Chip Muffin", 3.59, ""),
        ("Chocolate Chocolate Muffin", 3.59, ""), ("Corn Muffin", 3.59, ""),
        ("Croissant", 3.89, ""), ("Strawberry Cheese Danish", 3.59, ""),
        ("Cinnamon Raisin Muffin", 3.59, ""), ("Lemon Poppy Seed Muffin", 3.59, ""),
        ("Pumpkin Muffin", 3.59, ""), ("Everything Croissant", 3.89, ""),
        ("Almond Croissant", 4.29, ""),
    ],
    "Omelets": [
        ("American Omelet", 10.32, "Ham, American cheese, and tomato."),
        ("Mexican Omelet", 10.32, "Mushrooms, tomato, onions, jalapeño, and cheese."),
        ("Sausage & Potato Omelet", 10.32, "Sausage, home-fries, and cheddar cheese."),
        ("Simon's Omelet", 11.64, "Avocado, spinach, Feta cheese and salsa."),
        ("Western Omelet", 10.32, "Peppers, onions, and ham."),
        ("Veggie Omelet", 10.32, "Spinach, mushrooms, tomato, peppers, onions"),
        ("Mediterranean Omelet", 11.64, "Feta, olives, tomato, spinach, red onion"),
        ("Bacon Cheddar Omelet", 11.32, "Bacon, cheddar cheese, onions"),
        ("Italian Omelet", 11.64, "Pepperoni, mozzarella, peppers, basil"),
        ("Ham & Swiss Omelet", 10.32, "Virginia ham, Swiss cheese, mushrooms"),
        ("Turkey Avocado Omelet", 11.64, "Turkey, avocado, Swiss cheese, tomato"),
        ("Florentine Omelet", 11.64, "Spinach, sun-dried tomato, goat cheese"),
        ("Philly Steak Omelet", 12.64, "Steak, peppers, onions, provolone"),
        ("Garden Omelet", 10.32, "Broccoli, tomato, mushrooms, peppers"),
        ("Three Cheese Omelet", 10.32, "American, cheddar, mozzarella"),
    ],
    "Paninis": [
        ("California Panini", 15.95, "Turkey breast, tomato, avocado, Mozzarella cheese and Russian dressing."),
        ("Caprese Style Panini", 15.95, "Grilled chicken, mozzarella cheese, roasted red peppers, pesto sauce"),
        ("Chicken Fiesta Panini", 15.95, "Fried chicken cutlet, fresh mozzarella, roasted red peppers and spicy mayo."),
        ("Chicken Margherita Panini", 15.95, "Grilled chicken, tomatoes, fresh mozzarella, fresh basil and red onions."),
        ("Delightful Panini", 15.95, "Turkey breast, Swiss cheese, honey mustard and cole-slaw."),
        ("Desire Panini", 15.95, "House roast turkey breast, Swiss cheese, cole-slaw and Russian."),
        ("Italian Chicken Panini", 15.95, "Grilled chicken, pesto sauce, roasted red pepper, and fresh mozzarella."),
        ("Manhattan Panini", 15.95, "Roast beef, tomato, onions, bacon, Mozzarella cheese and Russian dressing."),
        ("Monterey Panini", 15.95, "Virginia ham, sharp Cheddar cheese, plum tomato and bacon, and Russian dressing."),
        ("Smokey Joe Panini", 15.95, "Smoked turkey, Cheddar cheese, bacon, crispy fried onions and Russian."),
        ("Sunset Panini", 15.95, "Turkey, mozzarella, tomato, avocado, ranch dressing."),
        ("Texas Panini", 15.95, "Fried chicken cutlet, bacon, fried onions, cheddar cheese and barbeque sauce."),
        ("Torino Panini", 15.95, "Fried chicken cutlet, Mozzarella, sundried tomato and pesto sauce."),
        ("Tuna Cheddar Panini", 15.95, "Tuna, Cheddar cheese and tomatoes."),
        ("BBQ Chicken Panini", 15.95, "Grilled chicken, BBQ sauce, cheddar, onions, pickles"),
    ],
    "Salads": [
        ("Chef Salad", 15.95, "Mixed lettuce, ham, eggs, turkey, carrots, Cheddar cheese, cucumber, tomatoes and green peppers."),
        ("Cobb Salad", 15.95, "Mixed lettuce, bacon, chicken, Provolone cheese, eggs, tomatoes, and black olives."),
        ("Greek Salad", 15.95, "Romaine lettuce, tomatoes, stuffed grape leaves, green peppers, Feta cheese and black olives."),
        ("Grilled Chicken Caesar Salad", 15.95, "Romaine lettuce, tomatoes, grilled chicken, Parmigiano cheese, croutons, and caesar dressing."),
        ("Grilled Chicken Salad", 15.95, "Romaine lettuce, tomatoes, grilled chicken, green bell peppers, shredded carrots and cucumbers."),
        ("Santa Fe Salad", 15.95, "Mixed lettuce, grilled chicken, beans, corn, Cheddar cheese, and crunchy cheese tortilla strips, and Santa Fe dressing."),
        ("Asian Sesame Salad", 15.95, "Mixed greens, grilled chicken, mandarin oranges, almonds, crispy wonton, sesame ginger dressing"),
        ("Mediterranean Salad", 15.95, "Romaine, grilled chicken, hummus, feta, cucumber, tomato, olives"),
        ("Steak Salad", 17.95, "Mixed greens, marinated steak, blue cheese, onion, tomato, balsamic"),
        ("Tuna Salad Plate", 15.95, "Fresh tuna salad over mixed greens with tomato and cucumber"),
        ("Southwest Chicken Salad", 15.95, "Grilled chicken, corn, black beans, avocado, cheddar, chipotle ranch"),
        ("Spinach & Strawberry Salad", 14.95, "Baby spinach, strawberries, goat cheese, pecans, balsamic"),
        ("Chicken Avocado Salad", 16.95, "Grilled chicken, avocado, mixed greens, tomato, ranch"),
        ("Buffalo Chicken Salad", 15.95, "Crispy buffalo chicken, romaine, blue cheese, celery, tomato"),
        ("Garden Salad", 10.95, "Mixed greens, tomato, cucumber, carrot, croutons"),
    ],
    "Sliced Cold Cuts": [
        ("American cheese 1/4 lb.", 2.99, ""), ("American cheese 1/2 lb.", 5.99, ""),
        ("American cheese 1 lb.", 11.98, ""),
        ("Boars Head Bologna 1/4 lb.", 2.99, ""), ("Boars Head Bologna 1/2 lb.", 5.99, ""),
        ("Boars Head Buffalo Chicken 1/4 lb.", 3.99, ""), ("Boars Head Buffalo Chicken 1/2 lb.", 7.99, ""),
        ("Boars Head Honey Turkey 1/4 lb.", 3.99, ""), ("Boars Head Honey Turkey 1/2 lb.", 7.99, ""),
        ("Boars Head Oven Roast Chicken 1/4 lb.", 3.99, ""), ("Boars Head Oven Roast Chicken 1/2 lb.", 7.99, ""),
        ("Boars Head Pastrami 1/4 lb.", 4.49, ""), ("Boars Head Pastrami 1/2 lb.", 8.98, ""),
        ("House Roast Beef 1/4 lb.", 4.49, ""), ("House Roast Beef 1/2 lb.", 8.98, ""),
        ("House Roast Turkey 1/4 lb.", 3.99, ""), ("House Roast Turkey 1/2 lb.", 7.99, ""),
        ("Swiss cheese 1/4 lb.", 2.99, ""), ("Swiss cheese 1/2 lb.", 5.99, ""),
        ("Provolone cheese 1/4 lb.", 2.99, ""), ("Provolone cheese 1/2 lb.", 5.99, ""),
    ],
    "Snacks & Light Meals": [
        ("Yogurt Parfait", 6.99, "Greek yogurt with granola and berries"),
        ("Overnight Oats & Berries", 6.99, "Oats soaked overnight with fresh berries"),
        ("Peanut Butter & Chocolate Overnight Oats", 6.99, "Oats with peanut butter and chocolate"),
        ("Strawberry Yogurt Parfait", 6.99, "Strawberry yogurt layered with granola"),
        ("Fruit Cup", 5.99, "Seasonal mixed fruit"),
        ("Hummus & Veggie Cup", 6.49, "Hummus with carrots, celery, and cucumber"),
        ("Trail Mix Cup", 4.99, "Mixed nuts, dried fruit, and chocolate"),
        ("Granola Bar", 2.99, "Honey oat granola bar"),
        ("Protein Bites", 5.99, "Chocolate peanut butter protein balls"),
        ("Cottage Cheese & Fruit", 6.49, "Cottage cheese with fresh seasonal fruit"),
        ("Avocado Toast Cup", 7.99, "Smashed avocado with seasoning"),
        ("Greek Yogurt Bowl", 6.99, "Greek yogurt with honey and walnuts"),
        ("Chia Pudding", 6.49, "Chia seeds with almond milk and berries"),
        ("Energy Smoothie Cup", 7.49, "Banana, peanut butter, protein powder, almond milk"),
        ("Veggie Sticks & Ranch", 4.99, "Carrot, celery, and cucumber sticks with ranch"),
    ],
}


def seed_menu_items(conn):
    print("Seeding menu items...")
    count = 0
    with conn.cursor() as cur:
        for cat_name, items in MENU_DATA.items():
            cur.execute("SELECT id FROM categories WHERE name = %s", (cat_name,))
            row = cur.fetchone()
            if not row:
                print(f"  Warning: category '{cat_name}' not found, skipping")
                continue
            cat_id = row[0]
            for name, price, desc in items:
                cur.execute(
                    "SELECT id FROM menu_items WHERE name = %s AND category_id = %s",
                    (name, cat_id),
                )
                if cur.fetchone():
                    continue
                cur.execute(
                    """INSERT INTO menu_items (category_id, name, description, price, is_available)
                       VALUES (%s, %s, %s, %s, true)""",
                    (cat_id, name, desc, price),
                )
                count += 1
        conn.commit()
    print(f"  Seeded {count} menu items")
